[project]
name = "predic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.7.0",
    "flask>=3.1.1",
    "torch>=2.7.1",
    "transformers>=4.52.4",
]
